---
# tasks file for initial-packages
- name: Install initial packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ initial_packages }}"

- name: Install extra initial packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ initial_packages_extra }}"
